dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./frontend/node_modules

install:
  - cd frontend && npm install

script:
  - cd frontend && npm run test
